### ISSUE TITLE
All the ' are displayed as &#39; when searching

### ISSUE THREAD

**Issue by PoisonFrog** [CogentRedTester/mpv-scripts#10]
This is really a minor issue but I'm wondering if there is a way I could fix it. Is it something I can fix editing the files or it's not possible?

Edit: I'm talking about the youtube-search script btw.

**Comment by CogentRedTester** [comment]
This looks like the YouTube API is saving video titles with HTML encoding. I'll try to have a look into fixing this in the next few days.

Could you give me some example searches and results that I can test with?

**Comment by PoisonFrog** [comment]
> This looks like the YouTube API is saving video titles with HTML encoding. I'll try to have a look into fixing this in the next few days.
> 
> Could you give me some example searches and results that I can test with?

Any search that has videos with single quotation marks in the title.
It looks like this:
![pic](https://user-images.githubusercontent.com/74987652/124418373-d96c3d80-dd4a-11eb-8ee4-ea6dd136891b.png)

**Comment by CogentRedTester** [comment]
Should be fixed now, just confirm it has been fixed for you and if so close the issue.

**Comment by PoisonFrog** [comment]
> Should be fixed now, just confirm it has been fixed for you and if so close the issue.

It's fixed. Thank you! :)
