### ISSUE TITLE
Documentation: Unclear on how to set it up

### ISSUE THREAD

**Issue by RafeeDaBoy** [CogentRedTester/mpv-scripts#14]
Hi, I am a bit new to this. I moved all the scripts to `C:\Users\User1\AppData\Roaming\mpv\mpv\scripts` and I opened mpv. I can't seem to use all the features you've mentioned in the readme and I'd really appreciate it if you could tell me on how to set it up

![image](https://user-images.githubusercontent.com/69535896/151321352-cf141ab0-1436-4ced-ae01-beb49996918f.png)

**Comment by CogentRedTester** [comment]
All the scripts in this repository are separate with individual documentation at the top of each file.

**Comment by CogentRedTester** [comment]
Also, the base config folder mpv will use by default is `C:\Users\User1\AppData\Roaming\mpv\scripts`. If you've placed `mpv.exe` in that folder, then yes it could work, but using the `mpv` directoy next to the `exe` is considered very low priority and may be removed in the future. If the `exe` is in that folder you should either move it, or change the config directory to `C:\Users\User1\AppData\Roaming\mpv\portable_config\`.

**Comment by RafeeDaBoy** [comment]
Thanks a lot for clearing that up! It works now.
