### ISSUE TITLE
`command-timeout.lua`: `screenshot` command doesn't print any OSD message

### ISSUE THREAD

**Issue by xfzv** [CogentRedTester/mpv-scripts#18]
**Describe the bug**
Running `script-message command-timeout ["screenshot"] 2` works but the OSD message (`Screenshot - /path/to/screenshot`) isn't printed, unlike when running `screenshot`.

**To Reproduce**
1. Open any video file with `$ mpv --no-really-quiet /path/to/video`
2. In mpv, open the console
3. Run `screenshot`
4. `Screenshot - /path/to/screenshot`, is displayed in the terminal, in mpv console and as an OSD message
5. Run `script-message command-timeout ["screenshot"] 2`
6. The screenshot message is only printed in the terminal and in mpv console, not in the OSD

**Expected behaviour**
`script-message command-timeout ["screenshot"] 2` should behave like `screenshot` (the OSD message should be printed in mpv window)

**Please complete the following information:**
 - OS: Linux
 - mpv version: mpv 0.35.0

**Comment by CogentRedTester** [comment]
Add the osd-auto [prefix](https://mpv.io/manual/master/#input-command-prefixes) before the screenshot command.

**Comment by CogentRedTester** [comment]
I highly suggest using [delay-command.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/delay-command.lua) instead btw. delay-command has much simpler syntax and automatically adds osd-auto. The only reason to use command-timeout is if you want to be able to reset the timer when you send the command again.
