### ISSUE TITLE
youtube-search: curl not returning search list

### ISSUE THREAD

**Issue by NaiveInvestigator** [CogentRedTester/mpv-scripts#21]
**Describe the bug**
The script is not getting search results after giving user input.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter a search query
2. Press enter

**Expected behaviour**
Returns a list of search results.

**Please complete the following information:**
 - OS: Linux (Nobara Linux 37)
 - mpv version: 0.35.0
 - [mpv.log](https://github.com/CogentRedTester/mpv-scripts/files/11644708/mpv.log)

**Additional context**
I get this in my console.
```
[youtube_search] Search did not return a results list
[youtube_search] search failed - attempting fallback
[youtube_search] curl: (3) URL using bad/illegal format or missing URL
[youtube_search]
[youtube_search] Search did not return a results list
```

curl version:
```
curl 7.85.0 (x86_64-redhat-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.8 zlib/1.2.12 libidn2/2.3.4 nghttp2/1.51.0
Release-Date: 2022-08-31
Protocols: file ftp ftps http https 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz SPNEGO SSL threadsafe UnixSockets
```
Edit: added curl version if needed

**Comment by CogentRedTester** [comment]
Looks like you don't have a valid Youtube API key.

**Comment by CogentRedTester** [comment]
The latest commit should have added proper error messages for when the API key is invalid.

**Comment by NaiveInvestigator** [comment]
> Looks like you don't have a valid Youtube API key.

TYSM!!! That was definitely the issue here. Got an API key and now it works!!


> The latest commit should have added proper error messages for when the API key is invalid.
Edit: can you check.

can confirm it works!

```
[youtube_search] {
[youtube_search]   "error": {
[youtube_search]     "code": 403,
[youtube_search]     "message": "The request is missing a valid API key.",
[youtube_search]     "errors": [
[youtube_search]       {
[youtube_search]         "message": "The request is missing a valid API key.",
[youtube_search]         "domain": "global",
[youtube_search]         "reason": "forbidden"
[youtube_search]       }
[youtube_search]     ],
[youtube_search]     "status": "PERMISSION_DENIED"
[youtube_search]   }
[youtube_search] }
[youtube_search]  
[youtube_search] Search did not return a results list 
```
