### ISSUE TITLE
keep-session.lua: "auto_load" resize mpv window although mpv.conf "auto-window-resize=no"

### ISSUE THREAD

**Issue by Wassss** [CogentRedTester/mpv-scripts#23]
Without [`keep-session.lua`](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) :
1. Set [`auto-window-resize=no`](https://mpv.io/manual/stable/#options-auto-window-resize) in mpv.conf
2. Open mpv
3. Set whatever size for mpv window
4. Load a video file
5. mpv window keep his original size

With [`keep-session.lua`](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) :
1. Set [`auto-window-resize=no`](https://mpv.io/manual/stable/#options-auto-window-resize) in mpv.conf
2. Add [`keep-session.lua`](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) to "scripts" path
3. Open mpv
4. Set whatever size for mpv window
5. Load a video file
6. mpv keep his original window size
7. Close mpv
8. Open mpv
9. [`keep-session.lua`](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) `auto_load` the last video file
10. mpv change his window size

**Expected behaviour**
10. mpv keep his original window size

**Please complete the following information:**
 - OS: Windows 11
 - mpv version v0.36.0-707-gcb2b579f
 - [log.log](https://github.com/CogentRedTester/mpv-scripts/files/13231600/log.log)

**Comment by CogentRedTester** [comment]
I don't think this is specifically a problem with keep-session.lua. I suspect this might be mpv saving the window size on quit and restoring it when keep-session runs the file again. See the [watch-later-options](https://mpv.io/manual/master/#options-watch-later-options) option to configure this and test if that is your problem.

**Comment by CogentRedTester** [comment]
@Wassss If you don't say otherwise I'll mark this issue as closed.
