### ISSUE TITLE
keep-session: add an option to remeber only the last opened video, not the playlist

### ISSUE THREAD

**Issue by PleskarjevJanez** [CogentRedTester/mpv-scripts#24]
**Is your feature request related to a problem? Please describe.**
I want to use this script together with [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua), autoload.lua loads all files inside a folder into the playlist anytime you open a video, but keep-session.lua seems to override this playlist with its own (possibly outdated) playlist. This is a problem when I add new videos to a folder, that weren't there before when I last "saved my session".

**Describe the solution you'd like**
I would like an option in the config, which makes it so that the script only remembers the last video, not the whole playlist.

**Describe alternatives you've considered**
use a diffirent script for remembering the last video

**Additional context**
I'm not a programmer, so the reason for these 2 scripts not working together could be completely diffirent

**Comment by CogentRedTester** [comment]
Try the latest version of the script, there is a new option that should do this.

**Comment by PleskarjevJanez** [comment]
> Try the latest version of the script, there is a new option that should do this.

I tried the newest version and it seems like it broke everything. Never mind using this script together with autoload.lua, even by itself it doesn't seem to work anymore.

 If you put "load_playlist=no"  in script opts, the script seems to stop working alltogether (doesn't do anything if you try restoring the previous session with a keybind or with auto_load=yes).

If you set  "load_playlist=yes", the script works again except you don't maintain your last position in the playlist, instead it puts you at the begining of the playlist

I dont know if I should have opened a new issue for this so sorry about that, but thanks for the help!

**Comment by CogentRedTester** [comment]
I am not seeing that behaviour on my end, can you upload a log file of you trying to reload the session made with `--log-file=log.txt --msg-level=keep_session='debug',autoload='debug'`.

**Comment by CogentRedTester** [comment]
Actually, I did find similar behaviour if (and only if) you were trying to restore playback to the very first item in the playlist, but this bug only applies when `load_playlist=no`, it should not have broken `load_playlist=yes`. Still make a log file if the issue persists and download the new version of the script before doing so.

**Comment by CogentRedTester** [comment]
Ok, it turns out there was another bug, but it only showed up on Windows, which is why I didn't catch it earlier. On my side both options are now working with and without autoload on both Windows and Linux.

**Comment by PleskarjevJanez** [comment]
> Ok, it turns out there was another bug, but it only showed up on Windows, which is why I didn't catch it earlier. On my side both options are now working with and without autoload on both Windows and Linux.

Thanks for the help all works well now!
