### ISSUE TITLE
[cycle-profile] How to restore default profile?

### ISSUE THREAD

**Issue by KonoVitoDa** [CogentRedTester/mpv-scripts#26]
I've added this to mpv.conf:
```
[profile1]
profile-restore=copy
brightness=-50
contrast=100
```
And this to input.conf:
```
W   script-message cycle-profiles "profile1"
```

And it applies the custom profile correctly, but how do I restore the default one?
I've tried ```script-message cycle-profiles "profile1;profile1 restore"``` with no success.

**Comment by CogentRedTester** [comment]
The cycle-profile script predates the profile restore feature. I'd suggest using the [cycle-commands](https://github.com/CogentRedTester/mpv-scripts/blob/master/cycle-commands.lua) script instead, which you can use to replicate the behaviour:

`script-message cycle-commands "apply-profile profile1" "apply-profile profile1 restore"`

**Comment by vitormathews** [comment]
Thanks, that's what I've done already haha.

**Comment by vitormathews** [comment]
How can I make it show profile name and description like cycle-profile does?

**Comment by CogentRedTester** [comment]
I don't think you can automatically grab the profile description with this method, but you can print some text manually:

`script-message cycle-commands "apply-profile profile1 ; show-text 'applying profile1'" "apply-profile profile1 restore ; show-text 'restoring profile1'"`

---

Also, if you want to actually cycle between profiles you could do:

`script-message cycle-commands "apply-profile profile2 restore ; apply-profile profile1 ; show-text 'applying profile1'" "apply-profile profile1 restore ; apply-profile profile2 ; show-text 'applying profile2'"`

---

Or if you're using mpv v0.36+ you could use the user-data property and auto profiles:

mpv.conf:
```properties
[profile1]
profile-cond=user_data.profile == 'profile1'
profile-restore=copy

[profile2]
profile-cond=user_data.profile == 'profile2'
profile-restore=copy
```

input.conf:

```properties
script-message cycle-commands "set user-data/profile profile1; show-text 'applying profile1'" "set user-data/profile profile2 ; show-text 'applying profile2'"
```

**Comment by CogentRedTester** [comment]
I've written a modified version of `cycle-profile.lua` in PR #27 that support profile restoration and has nicer syntax. It probably works better than using cycle-commands.

**Comment by KonoVitoDa** [comment]
WOW, that was fast, thank you so much! ❤️

**Comment by CogentRedTester** [comment]
It would be nice if you could test if it works and let me know. It works for me, but it's always good to have an extra person test. This is also your opportunity to recommend any changes to how it works before I push the change to master.

**Comment by KonoVitoDa** [comment]
> It would be nice if you could test if it works and let me know. It works for me, but it's always good to have an extra person test. This is also your opportunity to recommend any changes to how it works before I push the change to master.
> 
> Edit: if it's working then we can close this issue.

Oh man, I'm so sorry, I got busy and hadn't even read this message before nor tested the new version. I'm afraid it's too late now, but I could finally test it, and it works fine to apply and un-apply a profiile for a first time, but if I press the keybind again after the profile-restore options is used, it won't work anymore (no profiles are applied). In my input.conf i put:
```e   script-message cycle-profiles profile profile-restore```

**Comment by CogentRedTester** [comment]
> Oh man, I'm so sorry, I got busy and hadn't even read this message before nor tested the new version. I'm afraid it's too late now, but I could finally test it, and it works fine to apply and un-apply a profiile for a first time, but not for a second. If I press the keybind again after the profile-restore options is used, it won't work anymore (no profiles are applied anymore). In my input.conf I put: `e script-message cycle-profiles profile profile-restore`
> 
> 1st `e` press: `profile` is applied; 2nd `e` press: `profile restore` is used and default profile is back; 3rd `e` press: nothing happens.

You're doing it wrong, you don't do `profile-restore` to restore the previous profile, that happens automatically. What you have tried to do is apply a profile called `profile` on the first `e`, and then apply a profile called `profile-restore` on the second `e`. There was also a bug that should have been fixed in the latest commit where the script would crash if you tried to apply an unknown profile, that's why you couldn't keep cycling.

**Comment by KonoVitoDa** [comment]
Ooooh, I see. I fixed it and now it works perfectly!
```e   script-message cycle-profiles profile1 profile2 profile3 ""```

I was afraid it wouldn't work properly with multiple profiles, but gladly I was wrong haha.
Again, thank you so much! ❤️
