### ISSUE TITLE
[profile-command.lua] How to use?

### ISSUE THREAD

**Issue by KonoVitoDa** [CogentRedTester/mpv-scripts#28]
I haven't understoond well what's the purpose of this script; does it allow the use of profile-conditional key bindings? So I could use RIGHT/LEFT arrow while viewing image files to go to the next /previous file? Currentlu I use the following auto profile:
```
[image-only]
profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart']
profile-restore=copy
osd-playing-msg=
```
My long-time desire would be to use different key bindings depending on the profile I'm using. Does this script make this possible?

**Comment by CogentRedTester** [comment]
Yes and no. This script allows you to automatically run mpv [input commands](https://mpv.io/manual/master/#list-of-input-commands) when a profile is applied. So for example this profile would print `image` to the OSD when the profile condition triggers:

```properties
[image-only]
profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart']
profile-restore=copy
osd-playing-msg=
script-opts-append=profile_command-cmd= show-text "image"
```
While doing profile specific bindings was never the intention of this script, it can be done when using this script in conjunction with mpv [input sections](https://mpv.io/manual/master/#input-sections). You can define a keybind in `input.conf` as being part of a specific input section, and enable the section using profiles:

`input.conf`:
```properties
LEFT {image-only} playlist-prev
```

`mpv.conf`:
```properties
[image-only]
profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart']
profile-restore=copy
osd-playing-msg=
script-opts-append=profile_command-cmd= enable-section image-only
```

Note that this will not work with `profile-restore`, you would need a separate profile that runs the `disable-section` command.

**Comment by KonoVitoDa** [comment]
> `input.conf`:
> 
> ```ini
> LEFT {image-only} playlist-prev
> ```
> 
> `mpv.conf`:
> 
> ```ini
> [image-only]
> profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart']
> profile-restore=copy
> osd-playing-msg=
> script-opts-append=profile_command-cmd= enable-section image-only
> ```

This worked, thank you very much!



> Note that this will not work with `profile-restore`, you would need a separate profile that runs the `disable-section` command.

I tried this, and it seemed to work:
```
[video-and-audio]
profile-cond=p['current-tracks/video'] or p['current-tracks/audio']
profile-restore=copy
script-opts-append=profile_command-cmd= disable-section image-only
```

Do you know of any better ```profile-cond``` syntax or of a better way to run it when I switch back to the default profile?

**Comment by CogentRedTester** [comment]
You could just invert the previous profile condition:

```properties
profile-cond=not (p['current-tracks/video/image'] and not p['current-tracks/video/albumart'])
```

**Comment by KonoVitoDa** [comment]
> You could just invert the previous profile condition:
> 
> ```ini
> profile-cond=not (p['current-tracks/video/image'] and not p['current-tracks/video/albumart'])
> ```

I don't know why, but it not worked.

**Comment by CogentRedTester** [comment]
This doesn't work?:

```properties
[image-only]
profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart']
profile-restore=copy-equal
osd-playing-msg=
script-opts-append=profile_command-cmd= enable-section image-only

[not-image-only]
profile-cond=not (p['current-tracks/video/image'] and not p['current-tracks/video/albumart'])
profile-restore=copy-equal
script-opts-append=profile_command-cmd= disable-section image-only
```

**Comment by KonoVitoDa** [comment]
Now it worked, lol, I can't figure out what I did wrong, but whatever.

By the way, probably not of your interest, but I after doing some tests I noticed the keybinds from the section {image-only} are not working well: almost always I press RIGHT to go to the next image file and it skips several files, even dozens sometimes; or I click LEFT and it won't go to the previous file, but to the next instead, or try to do both and bug; and this even occured with the default next/prev keybinds. Seems like it's some uosc-related bug, as it didn't occur when I removed uosc's folder from my scripts folder.

**Comment by CogentRedTester** [comment]
Input sections are not a widely used feature, so it's possible that uosc is doing something that messes with it. I'd suggest creating an issue on their issue tracker instead.

**Comment by KonoVitoDa** [comment]
> Input sections are not a widely used feature, so it's possible that uosc is doing something that messes with it. I'd suggest creating an issue on their issue tracker instead.

I would, but after doing more tests, I noticed the error also occurred with uosc disabled. I'll have to find a solution on my own, or simply give up haha. Thank you for all the help anyway.

**Comment by KonoVitoDa** [comment]
Good news, I found the culprit: it's the [reload.lua](https://github.com/4e6/mpv-reload/blob/master/reload.lua) script.

**Comment by KonoVitoDa** [comment]
I don't know how, but adding a mp.command at the profile-cond also works to enable sections:

```
[image]
profile-cond=p['current-tracks/video/image'] and not p['current-tracks/video/albumart'] and mp.command('enable-section image')
profile-restore=copy-equal
osd-playing-msg=""
prefetch-playlist
background=0.2

[not-image]
profile-cond=p['current-tracks/video/image'] == false and mp.command('disable-section image')
```

**Comment by CogentRedTester** [comment]
That's actually a really nice way of doing it. The [`mp.command`](https://mpv.io/manual/master/#lua-scripting-mp-command(string)) function returns true when the condition evaluates to true, so it works quite well. I'd say that's a better way of doing things than the `profile-command` script. I don't think that conditional auto profiles were added to mpv when I initially created the script.
