### ISSUE TITLE
Youtube-search: Need help to change the keybind in input.conf

### ISSUE THREAD

**Issue by uugaabuugaa** [CogentRedTester/mpv-scripts#29]
There's no problem for me using ctrl+y and shift+y. But I want to put it in a menu for uosc and add a control button for it. But I don't know what to put in input.conf to make it work. script-binding or script-message-to youtube-search open_search_input doesn't do anything and I don't know if it should do anything either. Any way I can make entering search or showing search suggestion a menu for uosc ?

**Comment by CogentRedTester** [comment]
Hmm, looks like right now you can do `script-binding youtube-search`.

**Comment by nobef** [comment]
@CogentRedTester 
[Here](https://github.com/PopeyeURS/ulyssescaballes-mpv.config/blob/904981c92896faa056d7d97649fd4d1b24f0494e/portable_config/input.conf#L36) I saw a cool implementation, I do not understand how to realize!

https://github.com/user-attachments/assets/a580ef4b-90f7-41bc-91e8-eab2b6922f8f

**Comment by CogentRedTester** [comment]
@nobef I do not know what you are asking.

**Comment by nobef** [comment]
@CogentRedTester 
Well, there's a youtube-search in his config (under the name uosc-youtube-search, which seems to be slightly modified). And as shown in the gif, he's added it to the uosc context menu. It's a great search implementation. However, I wanted to do the same with a vanilla component, but I couldn't.

**Comment by CogentRedTester** [comment]
It does seem cool, but I don't know how you'd do it.

**Comment by nobef** [comment]
@CogentRedTester Okay, I'll ask him. 😁
