### ISSUE TITLE
keep-session: If the last played file is deleted MPV will not open.

### ISSUE THREAD

**Issue by curiosport** [CogentRedTester/mpv-scripts#35]
keep-session desperately searches for the last opened file but it no longer exists, because it was deleted, in which case an empty MPV window should open but instead MPV does not even run.

**Comment by CogentRedTester** [comment]
Set `--idle=yes` in mpv settings.

**Comment by curiosport** [comment]
@CogentRedTester Yep, I did that before and it fixes the problem, however I miss the need to press space and have mpv play the last existing file.

**Comment by CogentRedTester** [comment]
Sorry, I'm not sure how setting mpv to idle prevents you from pressing space?

**Comment by curiosport** [comment]
I mean I would like that function of pressing space on an empty MPV screen to play the last existing file in the playback history.

**Comment by CogentRedTester** [comment]
This script is only designed to keep the single previous session, it's not a history script. If you want older history there are a whole bunch of history scripts on mpv's [User Scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) page that would likely work much better than `keep-session`.
