### ISSUE TITLE
New cycle-commands syntax error with sharp sign

### ISSUE THREAD

**Issue by Dupond** [CogentRedTester/mpv-scripts#6]
Hello,

I'm trying to convert my cycle-commands syntax to the new format, but it seems to fail each time a sharp sign must be used:

`V script-message cycle-commands [ [["set","sub-font","Sans"],["set","sub-color","#FFFF00"]] , [["set","sub-font","Sans"],["set","sub-color","#000000"]] ]`

It gives the following error:

> [cycle_commands] command syntax incorrect for string:  [ [["set","sub-font","Sans"],["set","sub-color","
> [cycle_commands] if you see quotes around the above string then try removing them from input.conf

Thanx for the help,
Best regards,
Dupond

**Comment by CogentRedTester** [comment]
Ok, I figured out the issue, sharp is the character used for comments, so we need to encapsulate it within a string. If there are characters adjacent to the outside quotation mark then the string won't be encapsulated, so we need spaces around the quotes.

However, that is not the only issue, JSON syntax requires the double quotes to be part of the actual string, but by properly encapsulating the string the double quotes will be removed, hence we need to put the quotes inside the quotation marks as well, which requires an escape character.

This should work:
` [ [["set","sub-font","Sans"],["set","sub-color", "\"#FFFF00\"" ]] , [["set","sub-font","Sans"],["set","sub-color", "\"#000000\"" ]] ] `

**Comment by CogentRedTester** [comment]
This is a bit annoying, but should only happen with a very limited number of special characters. Still, I may need to put this into the documentation, thanks for bringing it to my attention.

**Comment by CogentRedTester** [comment]
See https://github.com/CogentRedTester/mpv-scripts/commit/3314e3446b2faed3e7a2bc2aecc2f5716c5b9b1c for the new documentation.

**Comment by CogentRedTester** [comment]
Gonna leave this here in case anyone finds this:

Under the new syntax the command would be:
`V script-message cycle-commands "set sub-font Sans ; set sub-color \"#FFFF00\"" "set sub-font Sans ; set sub-color \"#000000\""`

Strings with Hashes in them still need quotation marks around them

**Comment by Dupond** [comment]
Thanx! I had even guessed what the new command would be by myself ;) Your new syntax is indeed much easier to read!
